version : '3'

services:
  api:
    build: .
    ports:
      - 8000:8000
    image: rest_echo:latest
    volumes:
      - ./:/go/src/rest_echo
    hostname: "terra.sepulsa.local"

networks: 
  default:
    external:
      name: my-shared-network